# This is a basic workflow that is manually triggered

name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: astrowatcher/github-pages-deploy-action@master
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BRANCH: master
          FOLDER: public
          BUILD_SCRIPT: yarn && yarn run build
