# This is a basic workflow that is manually triggered

name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test secrets use
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
